import SiteFooter from "@/components/SiteFooter";
import SiteHeader from "@/components/SiteHeader";
import { ArrowRight, Building2, Handshake, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { values } from "@/data/siteContent";
import { useSiteVisual } from "@/contexts/SiteVisualsContext";
import { useSiteContent } from "@/contexts/SiteContentContext";

export default function About() {
  const heroImage = useSiteVisual("aboutHero");
  const darkCtaImage = useSiteVisual("aboutDarkCta");
  const qrCode = useSiteVisual("aboutQrCode");
  const heroKicker = useSiteContent("about.hero.kicker");
  const heroTitle = useSiteContent("about.hero.title");
  const heroDescription = useSiteContent("about.hero.description");
  const darkCtaKicker = useSiteContent("about.darkCta.kicker");
  const darkCtaTitle = useSiteContent("about.darkCta.title");
  const qrKicker = useSiteContent("about.qr.kicker");
  const qrDescription = useSiteContent("about.qr.description");
  return <div className="min-h-screen bg-[#FBFCFF]"><SiteHeader /><main>
    <section className="relative isolate overflow-hidden bg-[#0B1233] py-24 text-white sm:py-28"><img src={heroImage} alt="" className="site-image-bright absolute inset-0 size-full object-cover opacity-88" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(7,12,44,.92)_0%,rgba(12,20,63,.66)_46%,rgba(12,20,63,.14)_100%)]" /><div className="brand-grid absolute inset-0 opacity-25" /><div className="container relative max-w-5xl"><p className="font-mono-brand text-[11px] uppercase tracking-[.2em] text-cyan-300">{heroKicker}</p><h1 className="mt-5 max-w-4xl font-display text-5xl font-bold tracking-[-.075em] sm:text-6xl">{heroTitle}</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-100">{heroDescription}</p></div></section>
    <section className="border-y border-slate-200 bg-white"><div className="container grid gap-12 py-20 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div className="relative min-h-80 overflow-hidden rounded-[2rem] bg-[radial-gradient(circle_at_22%_20%,#32c4e6_0%,transparent_24%),radial-gradient(circle_at_84%_78%,#6256de_0%,transparent_31%),linear-gradient(135deg,#0c1644,#1d3189)] p-8 text-white"><div className="absolute inset-0 brand-grid opacity-20" /><div className="relative"><span className="font-mono-brand text-xs uppercase tracking-[.2em] text-cyan-200">Propheties Technologies</span><p className="mt-28 max-w-xs font-display text-3xl font-bold tracking-[-.06em]">Construire ce qui vous permet d’avancer sereinement.</p></div></div><div><p className="font-mono-brand text-[11px] uppercase tracking-[.2em] text-[#078FBE]">Notre mission</p><h2 className="mt-4 font-display text-4xl font-bold tracking-[-.06em] text-[#111B42]">Mettre des fondations numériques solides derrière chaque ambition.</h2><p className="mt-6 leading-7 text-slate-600">Nous accompagnons hôtels, entreprises, institutions et administrations dans la conception d’environnements numériques fiables : des câbles jusqu’au cloud, du réseau à l’intelligence artificielle.</p><p className="mt-4 leading-7 text-slate-600">Notre rôle est de rendre les décisions techniques plus simples et les déploiements plus sûrs.</p></div></div></section>
    <section className="container py-20 sm:py-24"><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-end"><div><p className="font-mono-brand text-[11px] uppercase tracking-[.2em] text-[#078FBE]">Notre équipe</p><h2 className="mt-4 font-display text-4xl font-bold tracking-[-.06em] text-[#111B42]">Des expertises complémentaires au service d’un même projet.</h2></div><p className="max-w-xl leading-7 text-slate-600">Chaque intervention rassemble les compétences utiles à votre contexte : conseil, infrastructure, sécurité et accompagnement des usages. Cette organisation permet d’avancer avec une vision cohérente, de l’étude à la mise en service.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{[["01","Conseil & pilotage","Cadrer les priorités, rendre les décisions techniques lisibles et garder le cap."],["02","Infrastructure & sécurité","Concevoir des fondations réseau robustes et préserver les environnements critiques."],["03","Produits & usages","Mettre les technologies, outils collaboratifs et automatisations au service des équipes."]].map(([index,title,text]) => <article key={title} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-[0_18px_30px_-28px_rgba(20,45,110,.45)]"><span className="font-mono-brand text-xs text-[#08A3D6]">{index}</span><h3 className="mt-7 font-display text-xl font-bold tracking-[-.045em] text-[#111B42]">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></section>
    <section className="container py-20 sm:py-28"><div className="max-w-2xl"><p className="font-mono-brand text-[11px] uppercase tracking-[.2em] text-[#078FBE]">Nos valeurs</p><h2 className="mt-4 font-display text-4xl font-bold tracking-[-.06em] text-[#111B42]">Les principes qui guident chaque intervention.</h2></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{values.map((value, index) => <article key={value.title} className="rounded-3xl border border-slate-200 bg-white p-6"><span className="font-mono-brand text-xs text-[#08A3D6]">0{index + 1}</span><h3 className="mt-7 font-display text-xl font-bold tracking-[-.045em] text-[#111B42]">{value.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{value.text}</p></article>)}</div></section>
    <section className="bg-[#EEF5FC] py-20"><div className="container grid gap-5 md:grid-cols-3">{[[Building2,"Implantation locale","Une équipe basée à Abidjan, proche des réalités opérationnelles des organisations."],[Sparkles,"Vision durable","Des choix techniques documentés, évolutifs et adaptés à l’usage réel."],[Handshake,"Collaboration","Une relation de travail basée sur l’écoute, la clarté et la confiance."]].map(([Icon,title,text]) => { const IconComponent = Icon as typeof Building2; return <article key={title as string} className="rounded-3xl bg-white p-7"><IconComponent className="text-[#078FBE]" size={25}/><h3 className="mt-6 font-display text-xl font-bold tracking-[-.045em] text-[#111B42]">{title as string}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text as string}</p></article>; })}</div></section>
    <section className="border-y border-slate-200 bg-white"><div className="container grid divide-y divide-slate-200 py-5 sm:grid-cols-3 sm:divide-x sm:divide-y-0">{[["6","expertises IT présentées"],["4","valeurs qui nous guident"],["1","ancrage local : Abidjan"]].map(([figure,label]) => <div key={label} className="py-6 text-center sm:py-4"><p className="font-display text-4xl font-bold tracking-[-.06em] text-[#111B42]">{figure}</p><p className="mt-2 text-sm text-slate-600">{label}</p></div>)}</div></section>
    <section className="container py-20"><div className="relative isolate overflow-hidden rounded-[2rem] bg-[#111B42] p-8 text-white sm:p-12"><img src={darkCtaImage} alt="" className="site-image-bright absolute inset-0 -z-20 size-full object-cover opacity-62" /><div className="absolute inset-0 -z-10 bg-[linear-gradient(100deg,rgba(11,18,51,.95),rgba(11,18,51,.62))]" /><div className="relative flex flex-col justify-between gap-8 lg:flex-row lg:items-center"><div className="max-w-xl"><p className="font-mono-brand text-[11px] uppercase tracking-[.18em] text-cyan-300">{darkCtaKicker}</p><h2 className="mt-3 font-display text-3xl font-bold tracking-[-.06em]">{darkCtaTitle}</h2><Link href="/contact" className="mt-6 inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-bold text-[#111B42] transition hover:bg-cyan-100">Demander un devis <ArrowRight size={16} /></Link></div><div className="w-fit rounded-3xl bg-white p-3 text-center shadow-[0_18px_34px_-16px_rgba(0,0,0,.45)]"><img src={qrCode} alt="QR code de Propheties Technologies" className="mx-auto size-32 rounded-xl bg-white object-contain p-1 sm:size-36" /><p className="mt-2 font-mono-brand text-[10px] font-semibold uppercase tracking-[.16em] text-[#078FBE]">{qrKicker}</p><p className="mt-1 text-xs font-medium text-slate-600">{qrDescription}</p></div></div></div></section>
  </main><SiteFooter /></div>;
}
