import SiteFooter from "@/components/SiteFooter";
import SiteHeader from "@/components/SiteHeader";
import { contactDetails, services } from "@/data/siteContent";
import { useSiteVisual } from "@/contexts/SiteVisualsContext";
import { useSiteContent } from "@/contexts/SiteContentContext";
import { trpc } from "@/lib/trpc";
import { ArrowUpRight, CheckCircle2, Mail, MapPin, MessageCircle, Phone, Send } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

const blank = { name: "", email: "", service: "", message: "" };

export default function Contact() {
  const [form, setForm] = useState(blank);
  const heroImage = useSiteVisual("contactHero");
  const heroKicker = useSiteContent("contact.hero.kicker");
  const heroTitle = useSiteContent("contact.hero.title");
  const heroDescription = useSiteContent("contact.hero.description");
  const formTitle = useSiteContent("contact.form.title");
  const formDescription = useSiteContent("contact.form.description");
  const mapTitle = useSiteContent("contact.map.title");
  const mapDescription = useSiteContent("contact.map.description");
  const contact = trpc.contact.submit.useMutation({ onSuccess: () => { setForm(blank); toast.success("Votre demande a bien été envoyée."); }, onError: () => toast.error("Impossible d’envoyer la demande. Veuillez réessayer.") });
  const submit = (event: FormEvent) => { event.preventDefault(); contact.mutate(form); };
  const update = (key: keyof typeof blank, value: string) => setForm((current) => ({ ...current, [key]: value }));

  return <div className="min-h-screen bg-[#FBFCFF]"><SiteHeader /><main>
    <section className="relative isolate overflow-hidden bg-[#0B1233] py-24 text-white sm:py-28"><img src={heroImage} alt="" className="site-image-bright absolute inset-0 size-full object-cover opacity-90" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(7,12,44,.92)_0%,rgba(12,20,63,.66)_46%,rgba(12,20,63,.14)_100%)]" /><div className="brand-grid absolute inset-0 opacity-25" /><div className="container relative max-w-5xl"><p className="font-mono-brand text-[11px] uppercase tracking-[.2em] text-cyan-300">{heroKicker}</p><h1 className="mt-5 max-w-4xl font-display text-5xl font-bold tracking-[-.075em] sm:text-6xl">{heroTitle}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-100">{heroDescription}</p><div className="mt-9 flex flex-wrap gap-3"><a href={contactDetails.phoneHref} className="inline-flex h-12 items-center gap-2 rounded-full bg-[#18B7E8] px-5 text-sm font-extrabold text-[#07123B] transition hover:-translate-y-0.5 hover:bg-cyan-200"><Phone size={17} /> Appeler maintenant</a><a href={contactDetails.whatsappUrl} target="_blank" rel="noreferrer" className="inline-flex h-12 items-center gap-2 rounded-full border border-white/30 bg-white/10 px-5 text-sm font-bold text-white backdrop-blur transition hover:-translate-y-0.5 hover:bg-white/20"><MessageCircle size={17} /> WhatsApp</a></div></div></section>

    <section className="container -mt-7 relative z-10"><div className="grid gap-3 rounded-[1.6rem] border border-slate-200 bg-white p-3 shadow-[0_18px_45px_-28px_rgba(15,31,85,.34)] sm:grid-cols-2 xl:grid-cols-3">{[[Phone,"Téléphone",contactDetails.phoneLabel,contactDetails.phoneHref,"#EEF0FF","#242C90"],[MessageCircle,"WhatsApp officiel",contactDetails.secondaryPhoneLabel,contactDetails.whatsappUrl,"#E7F9F1","#087E59"],[Phone,"Ligne directe",contactDetails.secondaryPhoneLabel,contactDetails.secondaryPhoneHref,"#EFF8F1","#087E59"],[Mail,"E-mail général",contactDetails.email,`mailto:${contactDetails.email}`,"#EDF7FC","#078FBE"],[Mail,"Direction",contactDetails.directorEmail,`mailto:${contactDetails.directorEmail}`,"#F7EDFD","#B92BC3"],[Mail,"E-mail complémentaire",contactDetails.additionalEmail,`mailto:${contactDetails.additionalEmail}`,"#FDF6EA","#A86108"]].map(([Icon,label,value,href,bg,color]) => { const IconComponent = Icon as typeof Phone; const isWhatsapp = String(label).startsWith("WhatsApp"); return <a key={label as string} href={href as string} target={isWhatsapp ? "_blank" : undefined} rel={isWhatsapp ? "noreferrer" : undefined} className="group flex min-w-0 items-center gap-3 rounded-2xl px-4 py-4 transition hover:bg-slate-50"><span style={{ backgroundColor: bg as string, color: color as string }} className="grid size-10 shrink-0 place-items-center rounded-xl"><IconComponent size={18}/></span><span className="min-w-0"><span className="block font-mono-brand text-[10px] uppercase tracking-[.15em] text-slate-400">{label as string}</span><span className="mt-1 block truncate text-sm font-bold text-[#111B42]">{value as string}</span></span><ArrowUpRight size={16} className="ml-auto shrink-0 text-slate-300 transition group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-[#B92BC3]" /></a>})}</div></section>

    <section className="container grid gap-12 py-20 lg:grid-cols-[.84fr_1.16fr] lg:py-24"><aside><p className="font-mono-brand text-[11px] uppercase tracking-[.2em] text-[#B92BC3]">Échangez avec nous</p><h2 className="mt-4 font-display text-4xl font-bold tracking-[-.065em] text-[#111B42]">Une réponse adaptée à votre contexte.</h2><p className="mt-6 max-w-md leading-7 text-slate-600">Qu’il s’agisse d’un projet d’infrastructure, d’un besoin de support ou d’une réflexion sur la sécurité, donnez-nous quelques éléments. Nous reviendrons vers vous avec clarté.</p><div className="mt-9 rounded-3xl bg-[linear-gradient(145deg,#151470_0%,#2738A0_58%,#06A8D7_150%)] p-6 text-white"><p className="font-mono-brand text-[10px] uppercase tracking-[.18em] text-cyan-200">Localisation</p><div className="mt-5 flex gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-white/12 text-cyan-200"><MapPin size={20}/></span><div><p className="font-display text-xl font-bold tracking-[-.045em]">Abidjan, Côte d’Ivoire</p><p className="mt-2 text-sm leading-6 text-slate-200">Retrouvez notre repère de localisation sur la carte et préparez votre itinéraire.</p></div></div><a href={contactDetails.mapDirectionsUrl} target="_blank" rel="noreferrer" className="mt-6 inline-flex items-center gap-2 rounded-full border border-white/25 px-4 py-2.5 text-xs font-bold text-white transition hover:bg-white/10">Ouvrir l’itinéraire <ArrowUpRight size={15}/></a></div></aside>
      <form onSubmit={submit} className="relative overflow-hidden rounded-[2rem] border border-slate-200 bg-white p-6 shadow-[0_20px_45px_-35px_rgba(20,45,110,.5)] sm:p-8"><div className="absolute -right-16 -top-16 size-48 rounded-full bg-fuchsia-200/40 blur-3xl" /><div className="relative"><div className="flex items-center justify-between gap-4"><div><p className="font-mono-brand text-[10px] uppercase tracking-[.17em] text-[#078FBE]">Formulaire de projet</p><h2 className="mt-2 font-display text-3xl font-bold tracking-[-.06em] text-[#111B42]">{formTitle}</h2></div><span className="grid size-12 place-items-center rounded-2xl bg-[#EDF7FC] text-[#078FBE]"><Send size={20}/></span></div><p className="mt-4 text-sm leading-6 text-slate-600">{formDescription}</p><div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-sm font-bold text-[#111B42]">Nom<input required value={form.name} onChange={(e) => update("name", e.target.value)} className="h-12 rounded-xl border border-slate-200 bg-[#FBFCFF] px-4 text-sm outline-none transition focus:border-[#078FBE] focus:ring-4 focus:ring-cyan-100" placeholder="Votre nom" /></label><label className="grid gap-2 text-sm font-bold text-[#111B42]">E-mail<input required type="email" value={form.email} onChange={(e) => update("email", e.target.value)} className="h-12 rounded-xl border border-slate-200 bg-[#FBFCFF] px-4 text-sm outline-none transition focus:border-[#078FBE] focus:ring-4 focus:ring-cyan-100" placeholder="vous@entreprise.com" /></label></div><label className="mt-5 grid gap-2 text-sm font-bold text-[#111B42]">Service souhaité<select required value={form.service} onChange={(e) => update("service", e.target.value)} className="h-12 rounded-xl border border-slate-200 bg-[#FBFCFF] px-4 text-sm outline-none transition focus:border-[#078FBE] focus:ring-4 focus:ring-cyan-100"><option value="" disabled>Sélectionnez un service</option>{services.map((service) => <option key={service.title} value={service.title}>{service.title}</option>)}</select></label><label className="mt-5 grid gap-2 text-sm font-bold text-[#111B42]">Votre besoin<textarea required minLength={10} value={form.message} onChange={(e) => update("message", e.target.value)} className="min-h-32 rounded-xl border border-slate-200 bg-[#FBFCFF] p-4 text-sm outline-none transition focus:border-[#078FBE] focus:ring-4 focus:ring-cyan-100" placeholder="Décrivez brièvement votre besoin, votre contexte ou votre projet." /></label><button disabled={contact.isPending} className="mt-6 inline-flex h-12 items-center gap-2 rounded-full bg-[#242C90] px-6 text-sm font-bold text-white shadow-[0_14px_26px_-16px_rgba(36,44,144,.95)] transition hover:-translate-y-0.5 hover:bg-[#141b70] disabled:cursor-not-allowed disabled:opacity-60">{contact.isPending ? "Envoi en cours…" : formTitle} {!contact.isPending && <CheckCircle2 size={17} />}</button></div></form>
    </section>

    <section className="border-y border-slate-200 bg-white py-16 sm:py-20"><div className="container"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="font-mono-brand text-[11px] uppercase tracking-[.2em] text-[#078FBE]">Nous situer</p><h2 className="mt-3 font-display text-3xl font-bold tracking-[-.06em] text-[#111B42]">{mapTitle}</h2></div><a href={contactDetails.mapDirectionsUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm font-bold text-[#242C90] hover:text-[#B92BC3]">Obtenir un itinéraire <ArrowUpRight size={16}/></a></div><div className="grid overflow-hidden rounded-[2rem] border border-slate-200 bg-[#EDF7FC] shadow-[0_18px_40px_-32px_rgba(20,45,110,.45)] lg:grid-cols-[.78fr_1.22fr]"><div className="flex min-h-[300px] flex-col justify-center bg-[linear-gradient(145deg,#101A59,#20389C_62%,#08A8D8_150%)] p-7 text-white sm:p-10"><p className="font-mono-brand text-[10px] uppercase tracking-[.18em] text-cyan-200">Repère géographique</p><p className="mt-4 max-w-sm font-display text-3xl font-bold tracking-[-.055em]">Propheties Technologies est basée à {mapTitle}.</p><p className="mt-4 max-w-sm text-sm leading-6 text-slate-200">{mapDescription}</p><a href={contactDetails.mapDirectionsUrl} target="_blank" rel="noreferrer" className="mt-7 inline-flex w-fit items-center gap-2 rounded-full bg-white px-4 py-3 text-sm font-bold text-[#111B42] transition hover:bg-cyan-100">Ouvrir dans Google Maps <ArrowUpRight size={16}/></a></div><div className="relative flex min-h-[300px] items-center justify-center bg-[#F6F0E6] p-5 sm:p-8"><img src="/manus-storage/abidjan-location-reference_cd3ba302.png" alt="Carte de la Côte d’Ivoire avec Abidjan repérée" className="site-image-bright max-h-[390px] w-full object-contain" loading="lazy" /><p className="absolute bottom-3 right-4 rounded-full bg-white/90 px-3 py-1 font-mono-brand text-[9px] text-slate-600 shadow-sm">Repère général · source : CIA World Factbook</p></div></div></div></section>
  </main><SiteFooter /></div>;
}
