import SiteFooter from "@/components/SiteFooter";
import SiteHeader from "@/components/SiteHeader";
import { serviceExpertises } from "@/data/serviceExpertises";
import { services } from "@/data/siteContent";
import { useSiteVisual } from "@/contexts/SiteVisualsContext";
import { useSiteContents } from "@/contexts/SiteContentContext";
import { ArrowLeft, ArrowRight, CheckCircle2, CircleCheck, Sparkles } from "lucide-react";
import { Link, useRoute } from "wouter";

export default function ServiceDetail() {
  const [, params] = useRoute("/services/:slug");
  const service = services.find((item) => item.slug === params?.slug);
  const serviceImage = useSiteVisual(service?.visualSlot ?? "networkService");
  const methodImage = useSiteVisual(service?.methodVisualSlot ?? "methodNetwork");
  const detailCtaImage = useSiteVisual("serviceDetailDarkCta");
  const getContent = useSiteContents();
  const contentKey = service ? `service.${service.slug}` : "";
  const label = getContent(`${contentKey}.label`);
  const title = getContent(`${contentKey}.title`);
  const promise = getContent(`${contentKey}.promise`);
  const context = getContent(`${contentKey}.context`);
  const features = service?.features.map((_, index) => getContent(`${contentKey}.feature.${index + 1}`)) ?? [];
  const approach = service?.detail.approach.map((_, index) => getContent(`${contentKey}.approach.${index + 1}`)) ?? [];
  const outcomes = service?.detail.outcomes.map((_, index) => getContent(`${contentKey}.outcome.${index + 1}`)) ?? [];
  const subExpertises = service ? serviceExpertises.filter((item) => item.serviceSlug === service.slug) : [];

  if (!service) return <div className="min-h-screen bg-[#FBFCFF]"><SiteHeader /><main className="container py-28"><p className="font-mono-brand text-xs uppercase tracking-[.18em] text-[#078FBE]">Service introuvable</p><h1 className="mt-4 font-display text-4xl font-bold tracking-[-.06em] text-[#111B42]">Cette expertise n’est pas disponible.</h1><Link href="/services" className="mt-7 inline-flex items-center gap-2 font-bold text-[#242C90]"><ArrowLeft size={17} /> Retour aux services</Link></main><SiteFooter /></div>;

  return <div className="min-h-screen overflow-hidden bg-[#FBFCFF]"><SiteHeader /><main>
    <section className="relative isolate overflow-hidden bg-[#0B1233] text-white"><img src={serviceImage} alt="" className="site-image-bright absolute inset-0 size-full object-cover opacity-84" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(7,12,44,.93)_0%,rgba(12,20,63,.7)_45%,rgba(12,20,63,.17)_100%)]" /><div className="brand-grid absolute inset-0 opacity-25" /><div className="container relative py-20 sm:py-28"><Link href="/services" className="inline-flex items-center gap-2 font-mono-brand text-[10px] uppercase tracking-[.18em] text-cyan-200 transition hover:text-white"><ArrowLeft size={14} /> Toutes les expertises</Link><p className="mt-12 font-mono-brand text-[11px] uppercase tracking-[.2em] text-cyan-300">{label}</p><h1 className="mt-4 max-w-3xl font-display text-5xl font-bold tracking-[-.075em] sm:text-6xl">{title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-200">{promise}</p><Link href="/contact" className="mt-9 inline-flex h-12 items-center gap-2 rounded-full bg-[#18B7E8] px-6 text-sm font-extrabold text-[#07123B] transition hover:-translate-y-0.5 hover:bg-cyan-200 active:scale-[.97]">{getContent("serviceDetail.cta.label")} <ArrowRight size={17} /></Link></div></section>
    <section className="container grid gap-12 py-20 lg:grid-cols-[1.05fr_.95fr] lg:items-start sm:py-28"><div><p className="font-mono-brand text-[11px] uppercase tracking-[.2em] text-[#B92BC3]">{getContent("serviceDetail.intro.kicker")}</p><h2 className="mt-4 font-display text-4xl font-bold tracking-[-.065em] text-[#111B42]">{getContent("serviceDetail.intro.title")}</h2><p className="mt-7 max-w-2xl leading-8 text-slate-600">{context}</p><div className="mt-10 grid gap-3">{features.map((feature, index) => <div key={index} className="flex gap-3 rounded-2xl border border-slate-200 bg-white px-5 py-4 text-sm font-semibold text-[#111B42]"><CheckCircle2 size={18} className="shrink-0 text-[#0AA8D9]" />{feature}</div>)}</div></div><aside className="relative isolate overflow-hidden rounded-[2rem] bg-[linear-gradient(145deg,#17166B_0%,#0B2E71_44%,#0FAAD5_140%)] p-8 text-white shadow-[0_25px_50px_-30px_rgba(23,22,107,.62)]"><img src={methodImage} alt="" className="site-image-bright absolute inset-0 -z-10 size-full object-cover opacity-82" /><div className="absolute inset-0 -z-10 bg-[linear-gradient(100deg,rgba(11,18,51,.95),rgba(12,38,101,.78),rgba(8,163,214,.48))]" /><div className="absolute -right-14 -top-14 size-48 rounded-full bg-fuchsia-400/25 blur-2xl" /><div className="relative"><span className="grid size-12 place-items-center rounded-2xl border border-white/20 bg-white/10 text-cyan-200"><Sparkles size={22} /></span><p className="mt-8 font-mono-brand text-[10px] uppercase tracking-[.18em] text-cyan-200">{getContent("serviceDetail.method.kicker")}</p><ol className="mt-5 grid gap-5">{approach.map((step, index) => <li key={index} className="flex gap-4"><span className="font-mono-brand text-xs text-fuchsia-200">0{index + 1}</span><span className="text-sm leading-6 text-white">{step}</span></li>)}</ol></div></aside></section>
    <section className="bg-[#EDF7FC] py-20"><div className="container"><p className="font-mono-brand text-[11px] uppercase tracking-[.2em] text-[#078FBE]">{getContent("serviceDetail.outcomes.kicker")}</p><div className="mt-8 grid gap-5 md:grid-cols-3">{outcomes.map((outcome, index) => <article key={index} className="rounded-3xl bg-white p-7 shadow-[0_18px_35px_-30px_rgba(11,50,100,.36)]"><span className="font-mono-brand text-xs text-[#B92BC3]">0{index + 1}</span><p className="mt-8 font-display text-xl font-bold tracking-[-.045em] text-[#111B42]">{outcome}</p><CircleCheck className="mt-7 text-[#08A3D6]" size={22} /></article>)}</div></div></section>
    {subExpertises.length > 0 && <section className="container py-20 sm:py-24"><div className="max-w-3xl"><p className="editorial-kicker">Approfondir cette expertise</p><h2 className="mt-4 font-display text-4xl font-bold tracking-[-.065em] text-[#111B42]">Choisissez le sujet qui correspond à votre besoin.</h2><p className="mt-5 text-base leading-7 text-slate-600">Chaque intervention peut être étudiée séparément ou intégrée à une approche plus complète. Ouvrez une fiche pour voir le périmètre, les étapes et les livrables associés.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2">{subExpertises.map((expertise) => <Link key={expertise.slug} href={`/services/${service.slug}/${expertise.slug}`} className="group rounded-[1.6rem] border border-slate-200 bg-white p-6 transition hover:-translate-y-1 hover:border-fuchsia-200 hover:shadow-[0_20px_38px_-28px_rgba(126,48,163,.4)]"><p className="editorial-kicker !text-[#B92BC3]">{expertise.label}</p><h3 className="mt-3 font-display text-2xl font-bold tracking-[-.05em] text-[#111B42]">{expertise.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{expertise.summary}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#242C90] transition group-hover:text-[#B92BC3]">Voir le détail <ArrowRight size={16} className="transition group-hover:translate-x-1" /></span></Link>)}</div></section>}
    <section className="container py-20"><div className="relative isolate overflow-hidden rounded-[2rem] bg-[#111B42] p-8 text-white sm:flex sm:items-center sm:justify-between sm:p-12"><img src={detailCtaImage} alt="" className="site-image-bright absolute inset-0 -z-10 size-full object-cover opacity-64" /><div className="absolute inset-0 -z-10 bg-[linear-gradient(100deg,rgba(17,27,66,.94),rgba(17,27,66,.68),rgba(17,27,66,.42))]" /><div><p className="font-mono-brand text-[11px] uppercase tracking-[.18em] text-cyan-300">{getContent("serviceDetail.cta.kicker")}</p><h2 className="mt-3 max-w-xl font-display text-3xl font-bold tracking-[-.06em]">{getContent("serviceDetail.cta.title")}</h2></div><Link href="/contact" className="mt-6 inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-bold text-[#111B42] transition hover:bg-fuchsia-100 sm:mt-0">{getContent("serviceDetail.cta.label")} <ArrowRight size={16} /></Link></div></section>
  </main><SiteFooter /></div>;
}
