import SiteFooter from "@/components/SiteFooter";
import SiteHeader from "@/components/SiteHeader";
import { useSiteContent, useSiteContents } from "@/contexts/SiteContentContext";
import { useSiteVisual } from "@/contexts/SiteVisualsContext";
import { getServiceExpertiseDetail } from "@/data/serviceExpertiseDetails";
import { serviceExpertises } from "@/data/serviceExpertises";
import { services } from "@/data/siteContent";
import { ArrowLeft, ArrowUpRight, CheckCircle2, ClipboardCheck, Sparkles } from "lucide-react";
import { Link, useRoute } from "wouter";

function MissingExpertise() {
  return <div className="min-h-screen bg-[#FBFCFF]"><SiteHeader /><main className="container py-24 sm:py-32"><p className="editorial-kicker">Page introuvable</p><h1 className="mt-4 max-w-xl font-display text-5xl font-bold tracking-[-.07em] text-[#111B42]">Cette expertise n’est pas disponible.</h1><Link href="/services" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#242C90] px-5 py-3 text-sm font-bold text-white"><ArrowLeft size={16} />Revenir aux services</Link></main><SiteFooter /></div>;
}

export default function ServiceExpertiseDetail() {
  const [, params] = useRoute("/services/:serviceSlug/:expertiseSlug");
  const expertise = serviceExpertises.find((item) => item.serviceSlug === params?.serviceSlug && item.slug === params?.expertiseSlug);
  const service = services.find((item) => item.slug === expertise?.serviceSlug);
  const content = useSiteContents();
  const title = useSiteContent(expertise ? `expertise.${expertise.serviceSlug}.${expertise.slug}.title` : "");
  const heroImage = useSiteVisual(service?.visualSlot ?? "networkService");

  if (!expertise || !service) return <MissingExpertise />;

  const detail = getServiceExpertiseDetail(expertise);
  const key = `expertise.${expertise.serviceSlug}.${expertise.slug}`;
  const copy = (field: string, fallback: string) => content(`${key}.${field}`) || fallback;
  const interventions = expertise.interventions.map((item, index) => copy(`intervention.${index + 1}`, item));
  const deliverables = expertise.deliverables.map((item, index) => copy(`deliverable.${index + 1}`, item));
  const analysisPoints = detail.analysisPoints.map((item, index) => copy(`analysis.${index + 1}`, item));
  const objectivePoints = detail.objectivePoints.map((item, index) => copy(`objective.${index + 1}`, item));
  const siblings = serviceExpertises.filter((item) => item.serviceSlug === service.slug && item.slug !== expertise.slug);

  return <div className="min-h-screen bg-[#FBFCFF]"><SiteHeader /><main>
    <section className="relative isolate overflow-hidden bg-[#0B1233] py-20 text-white sm:py-28"><img src={heroImage} alt="" className="site-image-bright absolute inset-0 -z-20 size-full object-cover opacity-70" /><div className="absolute inset-0 -z-10 bg-[linear-gradient(98deg,rgba(7,13,48,.97),rgba(12,25,74,.83),rgba(12,25,74,.5))]" /><div className="brand-grid absolute inset-0 -z-10 opacity-20" /><div className="container relative max-w-6xl"><Link href={`/services/${service.slug}`} className="inline-flex items-center gap-2 text-sm font-bold text-cyan-200 transition hover:text-white"><ArrowLeft size={16} />Retour à {service.label}</Link><p className="editorial-kicker mt-10 !text-cyan-200">{copy("label", expertise.label)}</p><h1 className="mt-4 max-w-4xl font-display text-5xl font-bold tracking-[-.075em] text-white sm:text-6xl">{title || expertise.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-100">{copy("summary", expertise.summary)}</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/contact" className="inline-flex h-12 items-center gap-2 rounded-full bg-[#18B7E8] px-5 text-sm font-extrabold text-[#07123B] transition hover:-translate-y-0.5 hover:bg-cyan-200">Demander un devis <ArrowUpRight size={17} /></Link><a href="#intervention" className="inline-flex h-12 items-center rounded-full border border-white/25 bg-white/10 px-5 text-sm font-bold text-white backdrop-blur transition hover:bg-white/20">Voir notre intervention</a></div></div></section>

    <section className="container grid gap-12 py-18 lg:grid-cols-[1.05fr_.72fr] lg:py-24"><div><p className="editorial-kicker">Comprendre cette solution</p><h2 className="mt-4 max-w-3xl font-display text-4xl font-bold tracking-[-.065em] text-[#111B42]">{copy("contextTitle", detail.contextTitle)}</h2><p className="mt-6 max-w-3xl text-base leading-8 text-slate-600">{copy("context", detail.context)}</p><p className="mt-5 max-w-3xl text-base leading-8 text-slate-600">{copy("intro", expertise.intro)}</p></div><aside className="rounded-[1.75rem] border border-cyan-100 bg-[#EDF9FD] p-6 sm:p-7"><span className="grid size-11 place-items-center rounded-2xl bg-white text-[#078FBE] shadow-sm"><Sparkles size={20} /></span><p className="mt-5 text-sm font-extrabold text-[#111B42]">Quand cette solution est utile</p><p className="mt-3 text-sm leading-7 text-slate-600">{copy("whenToUse", expertise.whenToUse)}</p></aside></section>

    <section className="border-y border-cyan-100 bg-[#F2FAFD] py-18 sm:py-24"><div className="container"><div className="max-w-3xl"><p className="editorial-kicker">Le périmètre de la prestation</p><h2 className="mt-4 font-display text-4xl font-bold tracking-[-.065em] text-[#111B42]">{copy("analysisTitle", detail.analysisTitle)}</h2></div><div className="mt-10 grid gap-4 md:grid-cols-3">{analysisPoints.map((point, index) => <article key={point} className="rounded-[1.6rem] border border-cyan-100 bg-white p-6 shadow-[0_18px_36px_-30px_rgba(15,102,137,.28)]"><span className="editorial-number">{String(index + 1).padStart(2, "0")}</span><p className="mt-7 text-base font-bold leading-7 text-[#111B42]">{point}</p></article>)}</div></div></section>

    <section id="intervention" className="border-y border-slate-200 bg-white py-18 sm:py-24"><div className="container"><div className="max-w-2xl"><p className="editorial-kicker">Notre intervention</p><h2 className="mt-4 font-display text-4xl font-bold tracking-[-.065em] text-[#111B42]">Nous avançons avec des étapes visibles.</h2><p className="mt-5 text-base leading-7 text-slate-600">Le niveau d’intervention est ajusté à votre contexte. Nous clarifions d’abord ce qui doit être résolu, puis nous mettons la solution en œuvre en gardant vos équipes informées.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{interventions.map((item, index) => <article key={item} className="rounded-[1.6rem] border border-slate-200 bg-[#FBFCFF] p-6 transition hover:-translate-y-1 hover:border-cyan-200 hover:shadow-[0_18px_36px_-28px_rgba(16,92,142,.45)]"><span className="editorial-number">{String(index + 1).padStart(2, "0")}</span><p className="mt-7 text-base font-bold leading-7 text-[#111B42]">{item}</p></article>)}</div></div></section>

    <section className="container grid gap-12 py-18 lg:grid-cols-[.85fr_1.15fr] lg:py-24"><div className="rounded-[1.9rem] bg-[linear-gradient(145deg,#13196A_0%,#263A9D_55%,#08A8D8_145%)] p-7 text-white sm:p-9"><span className="grid size-12 place-items-center rounded-2xl bg-white/12 text-cyan-200"><ClipboardCheck size={21} /></span><p className="mt-6 text-sm font-bold text-cyan-100">Ce que nous livrons</p><div className="mt-5 grid gap-4">{deliverables.map((item) => <div key={item} className="flex gap-3 text-sm leading-6 text-slate-100"><CheckCircle2 className="mt-0.5 shrink-0 text-cyan-200" size={17} />{item}</div>)}</div></div><div className="flex flex-col justify-center"><p className="editorial-kicker">Les résultats attendus</p><h2 className="mt-4 max-w-2xl font-display text-4xl font-bold tracking-[-.065em] text-[#111B42]">{copy("objectiveTitle", detail.objectiveTitle)}</h2><div className="mt-6 grid gap-3">{objectivePoints.map((point) => <div key={point} className="flex gap-3 text-base leading-7 text-slate-600"><CheckCircle2 className="mt-1 shrink-0 text-[#08A3D6]" size={18} />{point}</div>)}</div><Link href="/contact" className="mt-8 inline-flex w-fit items-center gap-2 rounded-full bg-[#242C90] px-5 py-3 text-sm font-bold text-white shadow-[0_14px_26px_-16px_rgba(36,44,144,.95)] transition hover:-translate-y-0.5 hover:bg-[#141b70]">Demander un devis <ArrowUpRight size={16} /></Link></div></section>

    {siblings.length > 0 && <section className="border-t border-slate-200 bg-white py-16"><div className="container"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="editorial-kicker">Dans la même expertise</p><h2 className="mt-3 font-display text-3xl font-bold tracking-[-.06em] text-[#111B42]">Autres solutions à explorer</h2></div><Link href={`/services/${service.slug}`} className="inline-flex items-center gap-2 text-sm font-bold text-[#242C90] hover:text-[#B92BC3]">Voir l’expertise complète <ArrowUpRight size={16} /></Link></div><div className="mt-8 grid gap-4 md:grid-cols-3">{siblings.map((item) => <Link key={item.slug} href={`/services/${service.slug}/${item.slug}`} className="group rounded-2xl border border-slate-200 bg-[#FBFCFF] p-5 transition hover:-translate-y-1 hover:border-fuchsia-200 hover:bg-white hover:shadow-[0_16px_32px_-24px_rgba(126,48,163,.45)]"><p className="editorial-kicker !text-[#B92BC3]">{item.label}</p><p className="mt-3 font-display text-lg font-bold tracking-[-.04em] text-[#111B42]">{item.title}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-[#242C90]">En savoir plus <ArrowUpRight size={15} className="transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></span></Link>)}</div></div></section>}
  </main><SiteFooter /></div>;
}
